version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data